---
functional:
  - Система должна позволять двум игрокам одновременно видеть код, который пишет друг друг, и следить за ходом решения задачи в реальном времени.
  - Система должна предоставить библиотеку задач различных уровней сложности, которые игроки могут выбрать для соревнования.
  - Система должна отслеживать количество побед, поражений и вычислять рейтинг каждого игрока, отображать глобальный рейтинг-лист.
  - Система должна предоставить возможность соревноваться с искусственным интеллектом для тренировки навыков.
  - Система должна иметь возможность приглашать конкретного друга на игровую сессию или дождаться случайного соперника так же создать сылку на присоединение к игре.
  - Система должна поддерживать выполнение кода на различных языках программирования (Python, JavaScript, Java, C++, Go и т.д.).
  - Система должна автоматически проверять решение пользователя против набора тестов и выдавать результат (пройдено/не пройдено).
  - Система должна позволять пользователям регистрироваться, входить в систему и управлять своим профилем.
  - Система должна сохранять историю всех игр пользователя с возможностью просмотра статистики, результатов и анализа прогресса.
  - Пользователь должен иметь возможность создать новую игровую сессию с выбранной задачей. 
  - Система должна показывать список открытых игр, которые ищут соперника. Пользователь может выбрать открытую игру и присоединиться к ней.
  - Система должна позволять другим пользователям присоединяться к запущенной игре в качестве зрителя для наблюдения за ходом соревнования без возможности участия.
non-functional:
  - Система должна быть способна обрабатывать большое количество трафика. Минимум 1000 одновременных пользователей без деградации производительности.
  - Система должна быть безопасной и защищать данные пользователя.
  - Сайт должен быть оптимизирован для скорости работы.
  - Сайт должен быть совместим с последними версиями браузеров Chrome, Firefox, Safari, Edge.
  - Сайт должен быть удобным на мобильных устройствах.
implicit:
  - Сайт должен быть разработан с учетом удобства использования. Интерфейс должен быть интуитивным, понятным для пользователей любого уровня.
  - Система должна обеспечивать честное соревнование между игроками, предотвращая читерство и манипуляции рейтингом.
  - Система должна предоставлять документацию, справку и FAQ для помощи пользователям в использовании платформы.
  - Платформа должна поддерживать развитие сообщества разработчиков через возможность общения, обмена опытом и совместного обучения.
  - Система должна иметь полное логирование ошибок и событий для отладки и анализа проблем.
  - Процесс установки расширения должен быть простым и доступным даже для неопытных пользователей.
  - Система должна оптимально работать не только на высокоскоростном интернете,но и на медленных соединениях.
