---
functional:
  - Система должна позволять двум игрокам одновременно видеть код, который пишет друг друг, и следить за ходом решения задачи в реальном времени.
  - Система должна предоставить библиотеку задач различных уровней сложности, которые игроки могут выбрать для соревнования.
  - Система должна отслеживать количество побед, поражений и вычислять рейтинг каждого игрока, отображать глобальный рейтинг-лист.
  - Система должна предоставить возможность соревноваться с искусственным интеллектом для тренировки навыков.
  - Система должна генерировать уникальные ссылки для приглашения конкретного друга на игровую сессию.
  - Система должна поддерживать выполнение кода на различных языках программирования (Python, JavaScript, Java, C++, Go и т.д.).
  - Система должна автоматически проверять решение пользователя против набора тестов и выдавать результат (пройдено/не пройдено).
  - Система должна позволять пользователям регистрироваться, входить в систему и управлять своим профилем.
  - Система должна сохранять историю всех игр пользователя с возможностью просмотра статистики, результатов и анализа прогресса.
non-functional:
  - Система должна быть способна обрабатывать большое количество трафика. Минимум 1000 одновременных пользователей без деградации производительности.
  - Система должна быть безопасной и защищать данные пользователя.
  - Сайт должен быть оптимизирован для скорости работы.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров Chrome, Firefox, Safari, Edge.
  - Сайт должен быть удобным на мобильных устройствах.
  - Изменения кода в соревновании должны отображаться у противника в реальном времени.
  -
implicit:
  - Сайт должен быть разработан с учетом удобства использования. Интерфейс должен быть интуитивным, понятным для пользователей любого уровня.
